<a href="https://colab.research.google.com/github/kosyunderbar/kosy_underbar/blob/main/Week04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


In [2]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [3]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: ignored

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arData.std()

1.4717934637713266

In [15]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2 

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [22]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: ignored

In [28]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
df.columns

Index(['score'], dtype='object')

In [31]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [32]:
df.sum()

score    60
dtype: int64

In [33]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [34]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
del df['score']

In [37]:
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [38]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [39]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [40]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [41]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0 -0.744823  0.093848 -0.902340  0.933217 -0.843780
1  0.591322 -0.634476 -2.143236  1.155039  0.442207
2  1.908007 -0.012932 -0.094025  0.903769 -0.569187
3  0.553388  1.266051  0.139110  0.257161 -1.280775
4 -0.121012 -1.266630 -0.526022 -0.342199 -2.352481

In [42]:
df.max()

A    1.908007
B    1.266051
C    0.139110
D    1.155039
E    0.442207
dtype: float64

In [43]:
df.min()

A   -0.744823
B   -1.266630
C   -2.143236
D   -0.342199
E   -2.352481
dtype: float64

In [44]:
df.mean()

A    0.437376
B   -0.110828
C   -0.705303
D    0.581397
E   -0.920803
dtype: float64

In [45]:
df.std()

A    0.988598
B    0.943048
C    0.897958
D    0.615412
E    1.020618
dtype: float64

In [46]:
df.cumsum()

A         B         C         D         E
0 -0.744823  0.093848 -0.902340  0.933217 -0.843780
1 -0.153500 -0.540628 -3.045576  2.088256 -0.401572
2  1.754506 -0.553560 -3.139601  2.992025 -0.970759
3  2.307894  0.712491 -3.000491  3.249186 -2.251533
4  2.186882 -0.554139 -3.526513  2.906987 -4.604015

In [47]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.437376 -0.110828 -0.705303  0.581397 -0.920803
std    0.988598  0.943048  0.897958  0.615412  1.020618
min   -0.744823 -1.266630 -2.143236 -0.342199 -2.352481
25%   -0.121012 -0.634476 -0.902340  0.257161 -1.280775
50%    0.553388 -0.012932 -0.526022  0.903769 -0.843780
75%    0.591322  0.093848 -0.094025  0.933217 -0.569187
max    1.908007  1.266051  0.139110  1.155039  0.442207

In [48]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.744823  0.093848 -0.902340  0.933217 -0.843780        X
1  0.591322 -0.634476 -2.143236  1.155039  0.442207        Y
2  1.908007 -0.012932 -0.094025  0.903769 -0.569187        X
3  0.553388  1.266051  0.139110  0.257161 -1.280775        Y
4 -0.121012 -1.266630 -0.526022 -0.342199 -2.352481        Z

In [49]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.581592  0.040458 -0.498182  0.918493 -0.706483
Y         0.572355  0.315788 -1.002063  0.706100 -0.419284
Z        -0.121012 -1.266630 -0.526022 -0.342199 -2.352481